#!/bin/bash
ARQUIVO_TMP="./potfile.tmp"
 
find ../www/ -type f -name \*.php > $ARQUIVO_TMP
xgettext -k_e -k__ -L PHP --from-code utf-8 --no-wrap -d messages -o messages.pot -f $ARQUIVO_TMP
 
rm -f $ARQUIVO_TMP
echo "messages.pot generated succesfully."
echo ''
cat translation.txt

#- See more at: http://www.devin.com.br/php-gettext/
